/**
 * Demo environment constants — Siliguri-focused realistic data.
 * Note: there is no geofences definition table; job sites + geofence_events
 * simulate location coverage.
 */
export const DEMO_ORG = {
  name: "MyTask Siliguri Demo Pvt Ltd",
  email: "iampapaisarkar@gmail.com",
  website: "https://mytask.demo",
  phone_number: "9832012345",
  phone_country_code: "+91",
  phone_country_iso: "IN",
  default_country: "IN",
  code: "SILDEMO1",
};

export const DEMO_USERS = [
  {
    key: "owner",
    first_name: "Papai",
    last_name: "Sarkar",
    email: "iampapaisarkar@gmail.com",
    firebase_uid: "FrWhaCfUPlY53tWNM1zrXArMHXW2",
    provider_id: "password",
    role: "owner",
    dob: "1992-05-14",
    phone_number: "9832011111",
    hourly_rate: 800,
  },
  {
    key: "moderator",
    first_name: "Rahul",
    last_name: "Sarkar",
    email: "iampapai619@gmail.com",
    firebase_uid: "e933eKj7S5djGEO0oOSsUd8iHYh2",
    provider_id: "password",
    role: "moderator",
    dob: "1990-08-22",
    phone_number: "9832022222",
    hourly_rate: 650,
  },
  {
    key: "manager",
    first_name: "Megha",
    last_name: "Sarkar",
    email: "iammeghachowdhury@gmail.com",
    firebase_uid: "qubEyPDOaxbA1A1SVpljsxgVK1N2",
    provider_id: "password",
    role: "manager",
    dob: "1994-11-03",
    phone_number: "9832033333",
    hourly_rate: 550,
  },
  {
    key: "staff1",
    first_name: "Pritth",
    last_name: "Sarkar",
    email: "iampritth@gmail.com",
    firebase_uid: "MmYxRuHygsM8p2tcaEjmsqAMca42",
    provider_id: "password",
    role: "staff",
    dob: "1998-02-17",
    phone_number: "9832044444",
    hourly_rate: 350,
  },
  {
    key: "staff2",
    first_name: "Bishakha",
    last_name: "Chowdhury",
    email: "iammeghasarkar@gmail.com",
    firebase_uid: "E6Pghs2SSrMgAOvqo7cXi9XUeP02",
    provider_id: "password",
    role: "staff",
    dob: "1997-07-09",
    phone_number: "9832055555",
    hourly_rate: 320,
  },
];

/** Job / activity sites around Siliguri (stand in for geofence definitions). */
export const SILIGURI_SITES = [
  { name: "Hill Cart Road Site", lat: 26.7271, lng: 88.3953, radius: 150 },
  { name: "Sevoke Road Depot", lat: 26.7402, lng: 88.4288, radius: 200 },
  { name: "Hakim Para Works", lat: 26.7105, lng: 88.4261, radius: 120 },
  { name: "Pradhan Nagar Hub", lat: 26.7318, lng: 88.4112, radius: 180 },
  { name: "Matigara Yard", lat: 26.7234, lng: 88.3821, radius: 250 },
  { name: "Champasari Site", lat: 26.755, lng: 88.412, radius: 160 },
  { name: "Salugara Works", lat: 26.768, lng: 88.435, radius: 140 },
  { name: "Medical More Point", lat: 26.719, lng: 88.418, radius: 100 },
  { name: "Junction Area Job", lat: 26.708, lng: 88.428, radius: 130 },
  { name: "City Centre Vicinity", lat: 26.7278, lng: 88.3958, radius: 170 },
];

export const LOOKUP_TABLES = [
  "SequelizeMeta",
  "system_roles",
  "organisation_roles",
  "invitation_status",
  "leave_categories",
  "timesheet_submission_frequencies",
  "pay_cycles",
  "rounding_intervals",
  "employment_status",
  "employment_types",
  "notification_status",
  "timesheet_activity_types",
  "states",
  "timesheet_status",
];

export const APP_TABLES = [
  "payouts",
  "geofence_events",
  "timesheet_task_activity_pairs",
  "timesheet_activity_logs",
  "timesheet_day_tasks",
  "timesheet_days",
  "timesheet_jobs",
  "timesheets",
  "notifications",
  "fcm_connections",
  "email_send_logs",
  "external_api_call_logs",
  "employee_invitations",
  "employee_payrolls",
  "employee_wages",
  "employee_address",
  "employees",
  "job_address",
  "jobs",
  "customers",
  "holiday_calendars",
  "payroll_calendars",
  "organisation_settings",
  "organisation_address",
  "user_organisation_roles",
  "organisations",
  "user_timezones",
  "user_sessions",
  "user_system_roles",
  "firebase_providers",
  "users",
];
